


import dbutil

warn = """
THIS SCRIPT WONT WORK WITHOUT PROPER DB INSTALLATION
IT IS INCLUDED IN GITHUB WITHOUT ADEQUATE DOCUMENTATION
UNTIL IT IS STABLE AND ABLE TO BE PROPERLY DOCUMENTED
"""
print(warn)

